language: php
php:
  - 5.5
  - 5.6

sudo: false

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always